- src/com/esotericsoftware/kryo/serializers/VersionFieldSerializer.java
This might be useful, particularly when dealing with cached objects.
> Add compatible option for VersionFieldSerializer

- README.md
The original code is error in compile.
> Fix bound type in README

- src/com/esotericsoftware/kryo/io/ByteBufferInputStream.java
Fix issue where ByteBufferInputStream violates the InputStream contract.
> https://github.com/EsotericSoftware/kryo/issues/337

- src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
Currently `CompatibleFieldSerializer` is using linear search, `O(n^2)`. 
This should be fine for small objects but not ok for objects with many fields.
If the number of fields in a blob is larger than a threshold, switch to binary search
I have encoutered class with > 100 fields regularly.
> Use binary search to find field in CompatibleFieldSerializer for objects with lots of fields.

- src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
- src/com/esotericsoftware/kryo/serializers/FieldSerializerConfig.java
- test/com/esotericsoftware/kryo/FieldSerializerTest.java
It is following pull request of #402.
I am sorry to make redundant pull request.
As you advise, I update against #414
> make FieldSerializer.serializeTransient usable

- src/com/esotericsoftware/kryo/Kryo.java
> Fix debug message when overwriting registration

- src/com/esotericsoftware/kryo/serializers/JavaSerializer.java
Due to a known Java issue ObjectInputStream might use a different ClassLoader
This can cause ClassNotFoundException
> Override ObjectInputStream ClassLoader

- src/com/esotericsoftware/kryo/util/IdentityMap.java
Fix read of uninitialized variable in constructor of IdentityMap
> Fix IdentityMap constructor

- src/com/esotericsoftware/kryo/Kryo.java
Add suggestions for fixing problems with anonymous classes to the
error that occurs when trying to deserialize them.
> error message for problems with anonymous classes

- README.md
I add ``import`` statements to the "Quickstart" section, so end user don't have to search around to find where are Kryo classes are.
> Adding import statements to "Quickstart" section.

- src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
- test/com/esotericsoftware/kryo/DefaultSerializersTest.java
Test cases for serialization of singletons
> Fix EsotericSoftware/kryo#548

- src/com/esotericsoftware/kryo/serializers/UnsafeCacheFields.java
Fix for the problem described in #593
> Allow negative offsets when getting a field value with sun.misc.Unsafe

- test/com/esotericsoftware/kryo/CopyTest.java
- test/com/esotericsoftware/kryo/GarbageCollectionTest.java
- test/com/esotericsoftware/kryo/KryoStringTest.java
- test/com/esotericsoftware/kryo/KryoTestCase.java
- test/com/esotericsoftware/kryo/ReferenceTest.java
- test/com/esotericsoftware/kryo/RegistrationTest.java
- test/com/esotericsoftware/kryo/SerializationBenchmarkTest.java
- test/com/esotericsoftware/kryo/SerializationCompatTest.java
- test/com/esotericsoftware/kryo/WarnUnregisteredClassesTest.java
- test/com/esotericsoftware/kryo/io/InputOutputTest.java
- test/com/esotericsoftware/kryo/io/UnsafeByteBufferInputOutputTest.java
- test/com/esotericsoftware/kryo/io/UnsafeInputOutputTest.java
- test/com/esotericsoftware/kryo/serializers/MapSerializerTest.java
- test/com/esotericsoftware/kryo/util/GenericsUtilTest.java
- test code in package com.esoterisoftware.kryo and com.esoterisoftware.kryo.util
- Add @Test, @Before annotations.
- Use assertion method in org.junit.Assert as possible as I can.
- Change to use Assert.assertArrayEquals for byte array comparison test.
> Move to Junit4 Style test code (Part 1).

- .travis.yml
- pom-main.xml
- pom.xml
- test/com/esotericsoftware/kryo/ReferenceTest.java
- test/com/esotericsoftware/kryo/SerializationCompatTest.java
* Updates maven plugins
* Add travis build/tests with jdk 9 + 11
Running tests with java 9+ required changes in test code.
Refs #626
> Add travis build/tests with java 9 + 11

- README.md
see https://github.com/altoo-ag/akka-kryo-serialization/issues/143
> Maintainer change of akka-kryo-serialization

- test/com/esotericsoftware/kryo/serializers/GenericsTest.java
This PR collects tests for all currently known issues with generics serialization as suggested in https://github.com/EsotericSoftware/kryo/issues/654#issuecomment-628847087.
I have simplified all test cases to the bare minimum required reproduce the issues.
> Test-cases for generics serialization issues

- test/com/esotericsoftware/kryo/serializers/GenericsTest.java
This PR adds an ignored test to demonstrate #721.
> #721 Add test

- test/com/esotericsoftware/kryo/serializers/GenericsTest.java
@magro: For some reason, there was a missing import in the PR you merged yesterday.
Shouldn't Travis also run for PRs and report broken builds?
> #721 Add missing import

- README.md
- src/com/esotericsoftware/kryo/Kryo.java
- src/com/esotericsoftware/kryo/util/DefaultGenerics.java
- src/com/esotericsoftware/kryo/util/Generics.java
- src/com/esotericsoftware/kryo/util/NoGenerics.java
- test/com/esotericsoftware/kryo/KryoTestCase.java
- test/com/esotericsoftware/kryo/SerializationCompatTest.java
This PR is a minimal implementation of the work done by @MarcMil in #683. 
The main difference is that is maintains full API compatibility and tests serialization compatibility when generics optimization is disabled.
> Minimal implementation of #683 that maintains API compatibility

- pom-main.xml
Pick up the latest and greatest object instantiation dependencies.
ReflectASM 1.11.8 -> 1.11.9
Objenesis 3.0.1 -> 3.1
> Upgrade of dependencies

- src/com/esotericsoftware/kryo/serializers/RecordSerializer.java
- test-jdk14/com/esotericsoftware/kryo/serializers/RecordSerializerTest.java
Change the `RecordSerializer` to use Core Reflection instead of `java.lang.invoke` / `Methodhandles`.
> revert to core reflection

- pom-main.xml
Bumps Objenesis to 3.2 to resolve #691
> #691 Bump Objenesis to 3.2

- pom.xml
otherwise you will run into ConcurrentModificationException such as in https://github.com/FasterXML/oss-parent/issues/27
> Upgrade Maven Bundle Plugin to 5.1.2 to support jdk15

- src/com/esotericsoftware/kryo/util/Util.java
- test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
- test/com/esotericsoftware/kryo/util/UtilTest.java
> #840 Ensure primitive types are assignable to Comparable/Serializable fields

- src/com/esotericsoftware/kryo/serializers/RecordSerializer.java
> #873 Set record component getter `accessible`

- README.md
Input class does not have a constructor with two int parameters
> fix: input constructor call error

- src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
- test/com/esotericsoftware/kryo/io/ByteBufferInputOutputTest.java
> #920 Align `ByteBufferOutput.writeAscii` with implementation in `Output`

- pom.xml
- test-kotlin/com.esotericsoftware.kryo/LambdaTest.kt
Pre-requisite for https://github.com/EsotericSoftware/kryo/issues/864
> Support for Kotlin tests
