.gitignore
src/com/esotericsoftware/kryo/serializers/EnumNameSerializer.java
test/com/esotericsoftware/kryo/serializers/EnumNameSerializerTest.java

With EnumNameSerializer, enum values are serialized with their name.
This serializer prevents reading wrong values when enum's order changed.

Fix for #321 EnumNameSerializer

---

src/com/esotericsoftware/kryo/Kryo.java

A few of the register(...) methods had javadocs that did not exactly align with the behavior of their methods, I believe as a result of changes that happened while moving to kryo version 3. This pull request brings the javadocs back into line. If it would be more desirable to alter the code to match the docs I would be happy to do so, but I thought it more likely that the code held the source of truth.
The primary differences were:
1) calling register for a class that already has a registration will not override the previous registration, unless register(...) was called with an explicit serializer
2) calling register with an explicit ID that is already in use for a different type will no longer throw an exception, instead it logs at the debug level
I believe that this partially resolves …

Alters the javadocs for the various register(...) methods to more correctly match behavior

---

src/com/esotericsoftware/kryo/io/Input.java
src/com/esotericsoftware/kryo/io/Output.java

The Netty project uses their own ByteBuffer implementation in their networking stack, and in order to provide Kryo Input/Output serialization via the Netty ByteBuffer implementation, the following 4 methods cannot be marked final.
This PR removes the final method keyword, so that Input/Output can be effectively overridden for 'native' usage in Netty.

Removed final modifier, so Input/Output can have all methods overridden

---

src/com/esotericsoftware/kryo/serializers/ExternalizableSerializer.java

Kryo in it's current state will not compile, since kryo.newInstance(type) returns type Object, and the implicit casting via generics does not take place. I only reverted the removal of casting made by change a0cb680 so that this class can now compile.
The specific error was:
ERROR
incompatible types
required: java.io.Externalizable
found:    java.lang.Object
Location: Line: 88:73
com/esotericsoftware/kryo/serializers/ExternalizableSerializer.java

Fixed compile errors by reverting cast externalizable in Serializer

---

src/com/esotericsoftware/kryo/io/Output.java
src/com/esotericsoftware/kryo/io/OutputChunked.java
test/com/esotericsoftware/kryo/InputOutputTest.java

Propagate flush to underlying stream

---

src/com/esotericsoftware/kryo/util/DefaultClassResolver.java

If running in an osgi environment the class loader that started kryo
can differ from the one that contains the class we want to load.
This introduces a fallback when class loading fails that
attempts to load the class with an osgi provided class loader.

Try to load classes with fallback that uses current ClassLoader.

---

src/com/esotericsoftware/kryo/serializers/JavaSerializer.java

This PR backports a change in `JavaSerializer` that fixes a problem with reusing an `Output` for serialization. See https://github.com/EsotericSoftware/kryo/issues/312 for details.

backport fix for Output reuse in JavaSerializer

---

src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
test/com/esotericsoftware/kryo/FieldSerializerTest.java

Fix for #370 
There were couple of approaches discussed in mailing list. Making it a config in kryo object seems to be easier.

copyTransient is not global

---

src/com/esotericsoftware/kryo/io/ByteBufferInput.java
src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
test/com/esotericsoftware/kryo/ByteBufferInputOutputTest.java

Fix positioning and setting of byteOrder on setting buffer + tests
The tests for the ByteBufferInput are aimed for externally given buffers.

Fix positioning 

---

src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
test/com/esotericsoftware/kryo/ByteBufferInputOutputTest.java

Test:
A case for when writing 
- varInt causes an overflow in the buffer
- varLong causes an overflow in the buffer
during writeVar*() a KryoException caused by require(int) did not revert the byteOrder

Fix #389 ByteBufferOutput: revert ByteOrder on overflow in require during writeVar*()

---

README.md

`CollectionSerializer.setElementClass(Class elementClass` is obsolete. Change it to use `CollectionSerializer.setElementClass(Class elementClass, Serializer serializer)`

Update README.md to use the new CollectionSerializer.setElementClass(..)

---

pom-main.xml
pom-shaded.xml
pom.xml
src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/DefaultArraySerializers.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializerAnnotationsUtil.java
src/com/esotericsoftware/kryo/serializers/FieldSerializerGenericsUtil.java
src/com/esotericsoftware/kryo/serializers/Generics.java
src/com/esotericsoftware/kryo/serializers/GenericsResolver.java

This is related to #342 (last change to Generics), and also related to #343 (reduce api).
Because Generics(Resolver) related methods are not considered to be part of the public api, no user should be affected. The removed methods and moved classes are added to the clirr ignore list.
The project version is changed back to 3.1.0-SNAPSHOT, because it had been accidentally incremented to 4.0.0 (now it's clear that the major version shall only be increased when serialization compatibility is
broken).
Btw, license header is changed because it had inconsistent line endings (and I don't know how to convince intellij to leave them inconsistent).

Move Generics(Resolver) to serializers, reduce visibility, go back to 3.1.0-SNAPSHOT

---

src/com/esotericsoftware/kryo/util/Util.java

Using existing classes might actually lead to the wrong result when used with other libraries like Robotium that provide those classes for non-Android systems.

Use system property to detect Android

---

src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializerConfig.java
test/com/esotericsoftware/kryo/FieldSerializerTest.java

(As adressed on the mailing list: https://groups.google.com/d/msg/kryo-users/G16daCijbWo/1igHI7WcBgAJ)
The `Kryo` class is more and more used for "global" configuration of serializers like `FieldSerializer` etc (here's another PR: #365). The semantics of such settings and especially for which serializer it's applied can often only be clarified via documentation.
This change introduces a `FieldSerializerConfig` class that encapsulates configuration for `FieldSerializer`. It allows to configure settings for all `FieldSerializer` instances created via `Kryo.getFieldSerializerConfig`. On each `FieldSerializer` the config can be changed/overridden, this is done directly on the serializer (instead e.g. requiring to invoke `fieldSerializer.getConfig.setSomeThing`) to stay binary compatible and …

Introduce FieldSerializerConfig to encapsulate config in Kryo

---

pom-main.xml
pom.xml
src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/ClosureSerializer.java
test/com/esotericsoftware/kryo/serializers/Java8ClosureSerializerTest.java

Closure is moved to ClosureSerializer because they're tightly coupled and this makes the connection more obvious.
This also renames `Kryo.isClousre` to `isClosure`, assuming that it was not used until now it's ignored regarding binary compatibility.
A test for closure serialization is added together with the required maven foo for compiler settings.
Fixes #299, refs #215

Make Closure public, moving it to ClosureSerializer

---

src/com/esotericsoftware/kryo/io/Output.java
test/com/esotericsoftware/kryo/InputOutputTest.java

Currently, the Output class allows the initial buffer size to be greater than the max buffer size. In some cases, we can observe an ArrayIndexOutOfBoundsException during an attempt to expand the buffer. The following test cases demonstrate the behaviour.
```
@Test
public void testNewOutputMaxBufferSizeLessThanBufferSize() {
int bufferSize = 2;
int maxBufferSize = 1;
Output output = new Output(bufferSize, maxBufferSize);
for (int i = 0; i < bufferSize; i++) {
output.writeByte(0);
}
output.writeByte(0);
}
@Test
public void testSetOutputMaxBufferSizeLessThanBufferSize() {
int bufferSize = 2;
int maxBufferSize = 1;
Output output = new Output(bufferSize, bufferSize);
output.setBuffer(new byte[bufferSize], maxBufferSize);
for (int i = 0; i < bufferSize; i++) {
output.writeByte(0);
} …
```

Throw exception if output buffer size is greater than max buffer size

---

src/com/esotericsoftware/kryo/Kryo.java
test/com/esotericsoftware/kryo/WarnUnregisteredClassesTest.java

With this option, unregistered classes are warned on kryos log instead of raise exception like the option registrationRequired do. 
This option is required mostly for processing large amount of data with third vendor libs, to see all classes that are not registered in the first running, instead of have to discover one class for each running. This happens with me using Spark and mlib.ALS
How to use:
```java
kryo.setWarnUnregisteredClasses(true)
```

Warn unregistered classes option

---

README.md
src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializerConfig.java
test/com/esotericsoftware/kryo/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/FieldSerializerInheritanceTest.java
test/com/esotericsoftware/kryo/FieldSerializerTest.java

My try to fix the PR #187. This solution here doesn't ignore "duplicate" fields, because they are not duplicate at all. They just belongs to different classes... 
Added a central method FieldSerializer#getFieldName(CachedField) that returns per default the field name. This behaviour is overriden in CompatibleFieldSerialzer and can be driven by the "extendedFieldNaming" boolean. If extendedFieldNaming is true, then Class simple name is added to the field name... and this helps to find the right field when deserializing. It's not perfect, but don't want to have it too verbose.
Any suggestions will be welcome!

Fix for CompatibleFieldSerializer inheritance issue

---

src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
test/com/esotericsoftware/kryo/ByteBufferInputOutputTest.java

Growing the ByteBuffer while writing varInt or varLong will change the byte order first, and then perform the require.
If the ByteBuffer needs to grow the setBuffer will again change the ByteOrder, but this time the one set by the varInt method. Thus the final ByteOrder was incorrect. (see [#464](https://github.com/EsotericSoftware/kryo/issues/464))

Fix growing ByteBufferOutput while writing varint (#464)

---

README.md

Updating README to reference the fact DefaultInstantiatorStrategy is static these days.

updating README to properly reference the DefaultInstantiatorStrategy

---

src/com/esotericsoftware/kryo/serializers/TaggedFieldSerializer.java
test/com/esotericsoftware/kryo/TaggedFieldSerializerTest.java

Check for overlapping tags

---

README.md
src/com/esotericsoftware/kryo/Kryo.java

Addresses #430 
The readme originally led me down the path of starting my registrations at 0 and wiping out the primitive registrations.
I suppose we could also log a warning if the ID is between 0 and 9.

Clarify default used registrations

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
test/com/esotericsoftware/kryo/CompatibleFieldSerializerTest.java

Correctly deserialize objects when fields are added to a Class with enough fields to trigger binary search in CompatibleFieldSerializer

#519 - Correctly deserialize objects when fields are added to a Class with enough fields to trigger binary search in CompatibleFieldSerializer

---

pom.xml

objenesis in the version 2.3 (https://github.com/easymock/objenesis/releases/tag/2.3) fixed important warning caused by using private ObjectStream api on Android N+. 
I'm a developer of Paper DB lib (https://github.com/pilgr/Paper) and happy to use Kryo serialization!
But I noticed users started to failing issues with a warning happening on read data on Android N and above `ObjectStreamClass.newInstance(Class<?>, long) is private API and will be removed in a future Android release`. 
I realized Objenesis fixed it, but Kryo 4.0 unfortunately uses outdated version. I temporary fixed this warning in the lib by forcing use of Objenesis 2.3. But would be awesome to have a new version of Kryo to include such dependency update. 
Thanks!

Fix warning on instantiate object on Android N+

---

src/com/esotericsoftware/kryo/io/ByteBufferInput.java
src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
src/com/esotericsoftware/kryo/io/Input.java
src/com/esotericsoftware/kryo/io/Output.java
src/com/esotericsoftware/kryo/io/Util.java

See:
* https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size
* https://github.com/apache/beam/pull/3189

Use relatively safe max size of java array

---

README.md

this pull request addresses  #497:
* add a section on serializing very large object graphs
* document limits on reference tracking + a workaround for avoiding them

add: documentation on very large object graphs

---

src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/DefaultSerializersTest.java

When an `Enum.class` instance is serialized (by `ClassSerializer`), this
causes the creation of the registered default serializer (`EnumSerializer`)
with this call chain:
```
ClassSerializer.write
-> Kryo.writeClass
-> DefaultClassResolver.writeClass
-> Kryo.getDefaultSerializer
-> ReflectionSerializerFactory.makeSerializer(kryo, EnumSerializer, Enum.class)
```
This is done so that `Kryo.writeClass` can write the class name or the id
of the serializer registration.
Until now, the `EnumSerializer` failed instantiation for a type with `null`
enum constants. This however is the case for `Enum.class` itself.
The creation of `EnumSerializer` for `Enum.class` is now allowed, under the
assumption that this happens in the context of the `Enum.class` serialization,
and that `write`/`read` on the …

Fix #529: Support serializing the Enum class object

---

README.md

This matches the other link in the README for MinLog which already points to Github

README: Change MinLog link away from Google Code

---

src/com/esotericsoftware/kryo/Serializer.java

Current com.esotericsoftware.kryo.Serializer::copy function determines immutability through its private field instead of it's public isImmutable() member (which docs actually mention). Since isImmutable() is virtual, this could break the copy api.
Note that this actually occurs in the Scala serializers provided by Twitter's Chill ([Traversable.scala](https://github.com/twitter/chill/blob/master/chill-scala/src/main/scala/com/twitter/chill/Traversable.scala)) and causes lot's of KryoException to be thrown in Apache Flink + Scala usage (one could argue the Twitter serializer implementations are to blame.. or chaning member isImmutable() to be **final** would be a preferred option, but that would break API compatibility)

Use public member instead of private field to resolve immutability

---

README.md

`CHANGES.md` is discontinued as of v3.0.2 - 3.0.3 (2015-07-26). The changelog is now part of the releases page.

Update changelog link

---

.settings.xml
.travis.yml
README.md

Tests with java8 and java7, on successful build publishes the artifacts to sonatype snapshots.
The inoio jenkins required too much maintenance and became unstable the last days.
We also need travis to be able to build/test with jdk 9/10.
An additional advantage of Travis are PR verification builds, so that it's immediately clear if anything got broken. 
@NathanSweet can you please activate the Travis build according to 2. from the [Getting Started guide](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI)?

Add travis build config

---

pom-main.xml
src/com/esotericsoftware/kryo/util/IntArray.java

and in consequence exclude it from clirr compatibility checks in order to fix the build broken by commit eb69e09c.

Declare IntArray being INTERNAL API

---

benchmarks/README.md
benchmarks/pom.xml
benchmarks/src/main/java/com/esotericsoftware/kryo/KryoBenchmarks.java
benchmarks/src/main/java/com/esotericsoftware/kryo/KryoFieldSerializersBenchmark.java
benchmarks/src/main/java/com/esotericsoftware/kryo/SampleObject1.java
pom.xml

This adds a maven module for JMH benchmarks and a sample benchmark
comparing the serialization performance of the different reflection
based (field) serializers (deserialization left to do).
To run benchmarks execute
```
mvn -f benchmarks/pom.xml compile exec:java
```
JMH options can be set via `-Dexec.args`, e.g.
```
mvn -f benchmarks/pom.xml compile exec:java -Dexec.args="-incl FieldSerializersBenchmark -f 2 -t 2 -wi 10 -i 10"
```

Add module for JMH benchmarks and sample benchmark

---

test/com/esotericsoftware/kryo/KryoAssert.java
test/com/esotericsoftware/kryo/io/ByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/ChunkedTest.java
test/com/esotericsoftware/kryo/io/InputOutputTest.java
test/com/esotericsoftware/kryo/io/UnsafeByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/UnsafeInputOutputTest.java
test/com/esotericsoftware/kryo/serializers/ArraySerializerTest.java
test/com/esotericsoftware/kryo/serializers/BeanSerializerTest.java
test/com/esotericsoftware/kryo/serializers/BlowfishSerializerTest.java
test/com/esotericsoftware/kryo/serializers/CollectionSerializerTest.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java
test/com/esotericsoftware/kryo/serializers/DeflateSerializerTest.java
test/com/esotericsoftware/kryo/serializers/EnumNameSerializerTest.java
test/com/esotericsoftware/kryo/serializers/ExternalizableSerializerTest.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerInheritanceTest.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/Java8ClosureSerializerTest.java
test/com/esotericsoftware/kryo/serializers/JavaSerializerTest.java
test/com/esotericsoftware/kryo/serializers/MapSerializerTest.java
test/com/esotericsoftware/kryo/serializers/TaggedFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/VersionedFieldSerializerTest.java

- Add Junit4 style annotation @Before,@Test.
- Change public method to private if it is possible.
- Stop extending TestCase class, If it is possible.
- Because There are deprecated methods in junit4,
I add static assertion class which is simple wrapper class.
I will Making KryoTestCase stop extending TestCase class at Part 3.

Move to Junit4 Style test code (Part 2).

---

test/com/esotericsoftware/kryo/CopyTest.java
test/com/esotericsoftware/kryo/KryoTestCase.java
test/com/esotericsoftware/kryo/ReferenceTest.java
test/com/esotericsoftware/kryo/SerializationBenchmarkTest.java
test/com/esotericsoftware/kryo/SerializationCompatTest.java
test/com/esotericsoftware/kryo/io/ByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/InputOutputTest.java
test/com/esotericsoftware/kryo/io/UnsafeByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/UnsafeInputOutputTest.java
test/com/esotericsoftware/kryo/serializers/CollectionSerializerTest.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java
test/com/esotericsoftware/kryo/serializers/EnumNameSerializerTest.java
test/com/esotericsoftware/kryo/serializers/ExternalizableSerializerTest.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerInheritanceTest.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java
test/com/esotericsoftware/kryo/serializers/Java8ClosureSerializerTest.java
test/com/esotericsoftware/kryo/serializers/MapSerializerTest.java
test/com/esotericsoftware/kryo/serializers/TaggedFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/VersionedFieldSerializerTest.java
test/com/esotericsoftware/kryo/util/GenericsUtilTest.java
test/com/esotericsoftware/kryo/util/PoolTest.java

Move to Junit4 Style test code(Part3). It is Final.
- Stop extending `org.junit.TestCase` at `KryoTestCase`. And I don't remove `KryoTestCase` :)
- Use assertion methods in `org.junit.Assert`, insted of methods in `org.junit.TestCase`
- Use suitable assertion method like `assertNull` `assertNotSame` `assertSame` `assertTrue` `assertFalse` insted of `assertEquals` if possible
- Remove unused throws statement at method signature.
- Use `@Test(expected = ExceptionClass.class)` where test expects to thrown exception
as long as test code will be simple. 
Because Junit4 hasn't suitable assertion method for testing exception thrown.
And At Junit5, good assertion method like `assertThrown` is introduced.
So, I think that it is not reasonable that I modify test code now where I can write more …

 Move to Junit4 Style test code(Part3)

---

README.md

Apache Dubbo™ (incubating) is a high-performance, java based open source RPC framework. It started incubating since 16th Feb, 2018.
In Dubbo, we have a serialization extension with Kryo, here it is: https://github.com/apache/incubator-dubbo/tree/master/dubbo-serialization/dubbo-serialization-kryo
We'll appreciate that if Dubbo can be placed under `products using Kryo`. Please let me know if other works needed. Thanks again.

add dubbo to products using Kryo

---

pom-main.xml

For the motivation see https://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html
reflectasm and minlog are updated to versions that provide an
Automatic-Module-Name as well.
objenesis is not updated, because it only provides Automatic-Module-Name
with 3.0.1, which requires java 1.8 (since 3.0.0) and therefore would
require kryo to switch from 1.7 to 1.8.
Refs #626

Add automatic module name to jar manifest

---

src/com/esotericsoftware/kryo/util/Pool.java

Ensure to reset the object before offering it to the pool to not obtain a not freed object in case of multi threading

Fix: Call reset before offering

---

.travis.yml
pom-main.xml
pom.xml
test/com/esotericsoftware/kryo/serializers/ClosureSerializerTest.java
test/com/esotericsoftware/kryo/serializers/OptionalSerializersTest.java
test/com/esotericsoftware/kryo/serializers/TimeSerializersTest.java

objenesis 3.0.1 comes with an Automatic Module Name, i.e. with that
kryo does no longer depend on any library that's not explicitely named.
For details / the motivation see also [this post](https://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html).
Because objenesis 3.0.1 only supports java 8, the source/target version
is pushed accordingly.

Update objenesis, push source/target version to 1.8

---

src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java

If a null StringBuilder or StringBuffer is provided, a NullPointerException occurs. Since these serializers both do `setAcceptsNull(true)`, a null is passed to their `write` methods which needs to be handled.

Avoid NPE writing StringBuilder/StringBuffer

---

src/com/esotericsoftware/kryo/serializers/ClosureSerializer.java

As my understanding, ClosureSerializer#write should write class names for captured args by writeClassAndObject instead of writeObject.

using writeClassAndObject instead of writeObject for captured args in ClosureSerializer#write

---

.travis.yml
pom-versioned.xml

* Fix parent version in pom-versioned.xml
* Attempt to fix travis build
* Use openjdk8 instead of oracle
* Use trusty to have the package available
* Get rid of java7 tests, this had been removed with #647 and
by accident was pulled in again with the merge of #652 which
still contained java7

Fix travis build

---

src/com/esotericsoftware/kryo/util/MapReferenceResolver.java

Right now the Object array inside the readObjects list is never trimmed so if a large object is cloned the JVM will never be able to reclaim the memory.

Realloc instead of clearing large array list.

---

src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/util/Generics.java
src/com/esotericsoftware/kryo/util/GenericsUtil.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java

This PR applies known fixes to resolve failing test-cases from #717.
It includes fixes suggested in:
- https://github.com/EsotericSoftware/kryo/pull/685
- https://github.com/EsotericSoftware/kryo/pull/707
All tests pass after applying these changes, but there might be additional corner cases as reported in #707. 
However, I believe that these 3 minor changes will resolve the vast majority of generics issues and should be reasonably safe:
- https://github.com/EsotericSoftware/kryo/commit/aefcde517ddd9ccf6020da52703b1e38c5e138a1 simply adds a missing handler for generic array types
- https://github.com/EsotericSoftware/kryo/commit/f2b6e292cc3f442140d54d3d62b6240004545f36 only applies in cases where an exception is currently thrown and can't really make matters worse
- …

Fixes for generic serialization issues

---

test/com/esotericsoftware/kryo/SerializationCompatTestData.java

This PR corrects a test failure when building with JDK11.
Locale providers changed with JDK11, resulting in slightly different default behavior:
- https://javachannel.org/posts/help-my-java-locale-is-wrong-in-jdk11/
- https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html#providers

Fix test when building with JDK11

---

src/com/esotericsoftware/kryo/util/GenericsUtil.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java

This PR is a follow-up to #718.
The original PR solved many currently known generics issues, but I uncovered two more corner cases while testing against my main app.
The test `ClassHierarchyWithChangingTypeVariableNames` shows that in some cases it is **impossible** to correctly resolve the generic type using the current generics logic. It relies on matching type parameter names, but the test uses different names for the same type in different levels of the inheritance hierarchy.
While this sounds like bad news, this knowledge leads to a very simple solution. Instead of throwing an exception when type parameters cannot be resolved, we simply have to give up and return the type variable.

#655 Fix generics corner cases

---

eclipse/.importorder
test/com/esotericsoftware/kryo/ReferenceTest.java
test/com/esotericsoftware/kryo/io/UnsafeByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/serializers/ArraySerializerTest.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java

This PR:
- Adds an `.importorder` file for Eclipse to make it easier for contributors to follow the project's code style.
- Applies the import order to all project files 
(4 files were changed. 1 was not following project style and 3 contained unused imports)

#683 Add .importorder file for Eclipse

---

.travis.yml
pom.xml
src/com/esotericsoftware/kryo/io/ByteBufferInput.java
src/com/esotericsoftware/kryo/io/ByteBufferInputStream.java
src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
src/com/esotericsoftware/kryo/unsafe/UnsafeByteBufferInput.java
src/com/esotericsoftware/kryo/unsafe/UnsafeByteBufferOutput.java
test/com/esotericsoftware/kryo/KryoTestCase.java
test/com/esotericsoftware/kryo/io/ByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/InputOutputTest.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java

This PR adds support for building with JDK11 while still being able to run tests with JDK8.
This enables Kryo to support JDK9+ classes like `java.util.ImmutableCollections` while still targeting JDK8 environments.
The same approach was taken to support JDK8 classes such as `Optional` (#362). 
This time things are a little more complicated though. JDK9 introduced new covariant return types for some methods on `ByteBuffer`, making the code backwards incompatible (see https://github.com/EsotericSoftware/kryo/issues/693#issuecomment-630096985).
The only way around this issue that does not require additional artifacts for newer JDK versions is to use implicit or explicit casts for these methods. This PR adds these casts. It doesn't look great and is brittle (we have to rely on CI builds to …

#693 JDK 11 Build

---

.travis.yml

This PR uses the same approach as the [default Travis build](https://docs.travis-ci.com/user/languages/java/#projects-using-maven) for Maven projects:
- The `install` phase runs `mvn install`
- The `script` phase runs `mvn test`
The only difference is that I dropped `-Dmaven.javadoc.skip=true` from the `install` phase so JavaDocs are still generated.

#693 Align `travis.yml` with default Travis behavior

---

src/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializers.java

I missed this in #727. The returned map should be immutable as well.

#693 Ensure copied map is immutable

---

src/com/esotericsoftware/kryo/util/Generics.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java

This PR resolves #721. It does not store generic type parameters if there aren't as many arguments as type parameters at the root of the generics hierarchy.
This is the cleanest solution I could think of and the previously failing test-case for #721 is the only test affected by the new condition. However, it is only a workaround. It might actually be possible to match the argument to the correct type parameter, but given that this is a rare corner case, I think we can live with not optimizing generics.

#721 Only store type variables if all of them have type arguments

---

src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/util/DefaultGenerics.java
src/com/esotericsoftware/kryo/util/Generics.java

This PR moves the check in `FieldSerializer` introduced in #654 into `DefaultGenerics` so all hierarchy verification is done in that class.
This is purely a cleanup PR and should not change any behavior.
@magro: Please take a look.

Consolidate generics hierarchy checks

---

src/com/esotericsoftware/kryo/util/MapReferenceResolver.java

This PR reverts initializing `MapReferenceResolver` collections with large capacities originally pushed in #705. 
For smaller object graphs this *significantly* increases overhead because these large maps have to be cleared after each graph is (de)serialized. The only advantage of initializing them at high capacity is that the *very first time* a larger graph is serialized, less resizing happens.
**Kryo 4**
Benchmark  |                     (objectType)  | (references) |   Mode |  Cnt  |      Score   
------------ | ------------- | ------------- | ------------- | ------------- | --:
FieldSerializerBenchmark.field     |   sample  |        **true** |  thrpt  |  5 |  **1211713,059** 
FieldSerializerBenchmark.field     |    media   |       **true** | thrpt  |  5  | **752031,612**
**Kryo 5 …

Improve MapReferenceResolver for small object graphs

---

src/com/esotericsoftware/kryo/serializers/ReflectField.java

This PR restores caching of serializers in `ReflectField` if the concrete `valueClass` of the field is known. 
@NathanSweet accidentally removed this in https://github.com/EsotericSoftware/kryo/commit/49e87d445163fe21cc64127ed823e13b90b6136b.
Note: We have to check on the `valueClass` instead of the `concreteType` because the same field can have different concrete generic types for different instances of the same class.
This is main reason why Kryo 5 is currently slower than Kryo 4. With this PR, Kryo 5 beats Kryo 4 in all benchmarks for `FieldSerializer`.
**Kryo 4**
Benchmark  |                     (objectType)  | (references) |   Mode |  Cnt  |      Score   
------------ | ------------- | ------------- | ------------- | ------------- | --:
FieldSerializerBenchmark.field  |      sample …

Restore caching of serializers if `valueClass` is known

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
src/com/esotericsoftware/kryo/util/Util.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/util/UtilTest.java

This PR attempts to resolve #744.
The original fix pushed by @NathanSweet in https://github.com/EsotericSoftware/kryo/commit/fb10f37ffec43d461b10d0cf4f17b950d12b6752 only works for fields that have the same type as the object stored in it. It fails for fields declared as super-types and interfaces.
This PR adds a check for primitive types originally proposed by @isaki in #670 and uses the concrete value class in all other instances.

#744 CompatibleFieldSerializer and fields declared as super-types

---

eclipse/code-format.xml
src/com/esotericsoftware/kryo/util/Pool.java
test/com/esotericsoftware/kryo/util/PoolTest.java

This PR resolves #746.
Limiting a pools maximum capacity is currently broken for two cases:
1. threadSafe=true softReferences=true
2. threadSafe=false softReferences=false
In the first case, `LinkedBlockingQueue.add` isn't overridden, so an `IllegalStateException` is thrown when reaching maximum capacity.
In the second case, the wrong method was overridden. `ArrayDeck` is not wrapped in a `SoftReferenceQueue` so `ArrayDeck.offer` is called directly. Internally, it uses `addLast` instead of `add` so the overridden method is never called.
I also made a slight change to the code formatting settings that preserves explicit linebreaks. It greatly improves the readability of the test-cases.

#746 Ensure pool maximum capacity is honored

---

src/com/esotericsoftware/kryo/serializers/CollectionSerializer.java

This PR adds a special case for `HashSet` to `CollectionSerializer`. It creates the set with the known capacity to avoid any resizing. 
We already have such special cases for `HashMap` and `ArrayList`.
The implementation is taken directly from JDK 11:
```
public HashSet(Collection<? extends E> c) {
map = new HashMap<>(Math.max((int) (c.size()/.75f) + 1, 16));
addAll(c);
}
```
The idea for this came up in a discussion on the [mailing list](https://groups.google.com/g/kryo-users/c/YDVladPC1F8/m/5N4ZGYe-EQAJ).
This approach is significantly faster for larger sets:
Benchmark  |                     (numItems)  | (mode) |   Mode |  Cnt  |      Score   
------------ | ------------- | ------------- | ------------- | ------------- | --:
HashSetBenchmark.read    |       1 |    reflection  | thrpt …

Initialize HashSet with large enough capacity

---

src/com/esotericsoftware/kryo/util/CuckooObjectMap.java
src/com/esotericsoftware/kryo/util/DefaultClassResolver.java

This PR adds back the `CuckooObjectMap` from Kryo 4 and uses it for mapping class registrations.
The new map implementations in Kryo 5 are ideal for read/write workloads. Nearly all maps in Kryo are heavily written to before they are cleared after each round of serialization. So this is a perfect fit.
There is one exception though: The map for class registrations in `DefaultClassResolver`. This map is never cleared and read much more often than written.
This is a use-case that the new maps do not handle well. Kryo 4's implementation of `ObjectMap` has significantly higher read throughput. This becomes especially noticeable when you serialize a large number of different classes. For maps with 1000-3000 entries, CuckooObjectMap has 40-60% faster reads:
**Kryo 4 ObjectMap**
Benchmark  | …

Use CuckooObjectMap from Kryo 4 for class registrations

---

src/com/esotericsoftware/kryo/util/MapReferenceResolver.java

This PR makes the maximum capacity for read and written references configurable.
The new map implementations in Kryo 5 are quite sensitive to resize operations. The map that tracks written objects in `MapReferenceResolver` is currently resized to a maximum capacity of 2048 after each serialization.
Serializing graphs with more than 2048 objects cause the map to grow and shrink constantly. Ideally, the maximum capacity for the reference resolver should be higher than the average size of the serialized graphs. This increases throughput by 15-20% for large graphs:
Benchmark  |  (maxCapacity) |   (numObjects) |     Mode |        Score   | Units
------------ | ------------- | ------------- |  ------------- |  --: | -------------
MapBenchmark.readWrite       |          2048     |     3000  | …

Customizable value for maximum capacity in MapReferenceResolver

---

README.md
src/com/esotericsoftware/kryo/Kryo.java

This PR removes `Poolable` from Kryo to prevent resetting the object graph state twice after each (de)serialization. 
`Poolable` is a good fit for `Input`/`Output`, but in the case of `Kryo` conflicts with the concept of `autoReset`.
Resolves #754.

#754 Unimplement `Poolable` from Kryo

---

src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java

The standard CollectionSerializer creates a deep copy of its structure, including children. The ArraysAsListSerializer surprisingly only created a shallow copy as it did not call kryo.copy(...) on its children. This has been fixed.

ArraysAsListSerializer should deep-copy

---

benchmarks/pom.xml
pom-main.xml
pom.xml
src/com/esotericsoftware/kryo/io/ByteBufferInput.java
src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
src/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializers.java
src/com/esotericsoftware/kryo/unsafe/UnsafeByteBufferInput.java
src/com/esotericsoftware/kryo/util/CuckooObjectMap.java

This PR adds the `formatter-maven-plugin` that allows users of any IDE to easily apply the project code format via `mvn formatter:format`.
It also bumps some plugin dependency versions and adds some plugin declarations to get rid of warnings in IntelliJ.
As a next step, project formatting could be validated during the build by adding the `formatter:validate` goal.

Add `formatter-maven-plugin` to easily apply Eclipse code format

---

src/com/esotericsoftware/kryo/Kryo.java
test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java

This is my first attempt to fix #771
Note that I'm not sure if there are any side effects of changing the ordering in the list of defaults.
So please review this thoroughly. 
I have included a set of tests that verifies all scenarios I could think of in this area.

Fix explicit KryoSerializer to have higher prio than implicit choices.

---

src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/SerializationCompatTest.java
test/com/esotericsoftware/kryo/serializers/MapSerializerTest.java

As the issue [#660 ] (https://github.com/EsotericSoftware/kryo/issues/660) mentioned, the kryo lacks of a default 'ConcurrentSKipListMap' serializer.
This is a fix for it.

Add a new ConcurrentSkipListMapSerializer

---

pom-main.xml

Downgrades the `maven-bundle-plugin`.
A bug in that plugin drops the Automatic-Module-Name set by the maven-jar-plugin:
https://issues.apache.org/jira/browse/FELIX-6312
https://issues.apache.org/jira/browse/FELIX-6337
Resolves #776

#776 Downgrade maven-bundle-plugin

---

src/com/esotericsoftware/kryo/Kryo.java
src/com/esotericsoftware/kryo/util/Util.java
test/com/esotericsoftware/kryo/WarnUnregisteredClassesTest.java

This PR adjusts the registration hint for `warnUnregisteredClasses` to use the canonical class name if available.
See #778

#778 Use canonical class name for registration hint if available

---

README.md

#781 Document that `endChunk` has to be called before closing the output

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/serializers/TaggedFieldSerializer.java
src/com/esotericsoftware/kryo/serializers/VersionFieldSerializer.java
src/com/esotericsoftware/kryo/util/DefaultGenerics.java
src/com/esotericsoftware/kryo/util/Generics.java
src/com/esotericsoftware/kryo/util/NoGenerics.java
test/com/esotericsoftware/kryo/KryoTestCase.java

This PR resolves #786. 
FieldSerializers currently violate the contract of `pushGenericType/popGenericType`. Under certain circumstances, a type is pushed but never popped resulting in an ever increasing array of generic types.
This PR ensures that `popGenericType` is called in all cases and adds an assertion for all round-trip tests that verifies that the generic types are empty after serialization.

#786 Balance `pushGenericType` and `popGenericType` for field serializers

---

src/com/esotericsoftware/kryo/serializers/ReflectField.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerTest.java

This PR catches `StackOverflowError` thrown by `FieldSerializer` and adds hint about enabling references to the error message.
Resolves #789.

#789 Catch StackOverflowError and add hint for enabling references

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/serializers/ReflectField.java
src/com/esotericsoftware/kryo/serializers/TaggedFieldSerializer.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/TaggedFieldSerializerTest.java

Resolves #774 
Resolves #784
This PR prevents re-using `ReflectField` serializers when using `CompatibleFieldSerializer` and `TaggedFieldSerializer`. 
Re-using serializers works for `FieldSerializer` because it only provides a concrete `valueClass` for final field types or if `fixedFieldTypes` is enabled. `CompatibleFieldSerializer ` and `TaggedFieldSerializer` *always* populate the `valueClass` with the last value they encounter.
I'm not fond of this solution but it is the only way to resolve this issue without breaking backwards compatibility.

#774 Do not re-use serializers for CompatibleFieldSerializer and TaggedFieldSerializer

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
src/com/esotericsoftware/kryo/util/Util.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/util/UtilTest.java

`CompatibleFieldSerializer` currently validates the read type against the field's `valueClass`. This does not work for classes with `Object` fields where the value class is updated on every read/write.
This PR adjusts the validation logic to compare against the field's `type` instead.

#774 Validate read types against field type instead of valueClass

---

src/com/esotericsoftware/kryo/util/DefaultGenerics.java
test/com/esotericsoftware/kryo/serializers/ParallelSerializationTest.java

Resolves #798.
Apparently, multiple instances of a type variable can be created in highly concurrent environments, so type variables need to be compared via object equality.

#798 Use equals to compare type variables

---

src/com/esotericsoftware/kryo/util/Pool.java

Prevent throwing exception on multi-threaded environment where two
concurrent threads can change state between these lines:
```
if (size() >= maximumCapacity) return false;
super.add(o);
```
what causes mentioned exception.

Prevent ISE Queue full #804

---

src/com/esotericsoftware/kryo/util/Util.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java

Add check for `Closure` marker class to `Util.isAssignableTo()`.
Resolves #821.

Support closures when validating types in CompatibleFieldSerializer

---

src/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializer.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java

#823 Fix `ArrayIndexOutOfBoundsException` in binary search logic

---

README.md

The badge shows the build status on OSS-Fuzz and links to the list of bugs (fixed ones for the general public, all bugs for maintainers).

Add OSS-Fuzz status badge

---

src/com/esotericsoftware/kryo/io/OutputChunked.java

Modify content： avoid flush repeatedly when has finished flushing.  
After my testing ,this modification can save cpu usage in high concurrency service.

avoid flush repeatedly when has finished flushing

---

src/com/esotericsoftware/kryo/serializers/RecordSerializer.java
test-jdk14/com/esotericsoftware/kryo/TestDataJava14.java
test-jdk14/com/esotericsoftware/kryo/serializers/RecordSerializerTest.java

The `RecordSerializer` currently fails to deserialize abstract/non-final component types, because it doesn't include concrete type information in the serialized bytes.
It would be possible to solve this in a backwards-compatible way, but that would force users to opt-in to the the correct behavior. I think we should make an exception in this case, break compatibility, and allow users who already have records serialized with the flawed implementation to selectively enable backwards-compatibility for existing records.
This will have to be documented clearly in the release notes for Kryo 5.2.0.
Resolves #847.

#847 Ensure that `RecordSerializer` can deal with subtypes

---

src/com/esotericsoftware/kryo/io/InputChunked.java
test/com/esotericsoftware/kryo/io/ChunkedTest.java

Buffer underflows set the buffer position to 0 while trying to resize the buffer. This prevents `InputChunked.nextChunk()` from advancing to the next chunk.
This PR ensures that that the buffer is at the final position of the chunk before advancing to the next chunk.
Resolves #834.

#834 Support skipping input chunks after a buffer underflow

---

README.md

When using kryo in a large scale distribute systems, we must face the problem that the  same jar with different versions.If using the built-in CompatibleFieldSerializer will get a bad performance. So we want to improve the performance.This is the JMH(Java MicroBenchmark result): 
```
Benchmark                                                      Mode  Cnt        Score                Error  Units
SerializerBenchmark.Kryo_Upstream_Compatible_DiffLayout1.run  thrpt   15   370660.262 ±  2967.346           ops/s
SerializerBenchmark.SCFS_DiffLayout1.run                      thrpt   15  1237834.811 ± 14960.798           ops/s
```
So We want add a link to session-compatible-fast-serializer so that if anyone encounter the same problem ,maybe session-compatible-fast-serializer  is a choice.

Add new link to session-compatible-fast-serializer project

---

src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java

This PR ensures that empty `PriorityQueue` can be deserialized by always providing an `initialCapacity` >= 1.
Resolves #865

#865 Ensure empty `PriorityQueue` can be deserialized

---

src/com/esotericsoftware/kryo/serializers/CachedFields.java

#882 Catch `LinkageError` when accessing fields via ReflectASM

---

src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java

I've added the new serializer to DefaultSeriailzers (even though it won't be used by default in Kryo 5). Is this OK? If not, let me know where it belongs.

#889 Serializer for java.sql.Timestamp which preserves nanoseconds

---

README.md
pom.xml
src/com/esotericsoftware/kryo/serializers/ClosureSerializer.java
src/com/esotericsoftware/kryo/util/Util.java
test-jdk11/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializersTest.java
test-jdk14/com/esotericsoftware/kryo/TestDataJava14.java
test/com/esotericsoftware/kryo/KryoTestCase.java
test/com/esotericsoftware/kryo/ReferenceTest.java
test/com/esotericsoftware/kryo/ReflectionAssert.java
test/com/esotericsoftware/kryo/SerializationBenchmarkTest.java
test/com/esotericsoftware/kryo/SerializationCompatTestData.java
test/com/esotericsoftware/kryo/Unsafe.java
test/com/esotericsoftware/kryo/io/UnsafeByteBufferInputOutputTest.java
test/com/esotericsoftware/kryo/io/UnsafeInputOutputTest.java
test/com/esotericsoftware/kryo/serializers/ClosureSerializerTest.java
test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/FieldSerializerTest.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java
test/com/esotericsoftware/kryo/serializers/OptionalSerializersTest.java

This PR attempts to fix as many tests as possible when running under JDK17 without any `add-opens` arguments.
Most tests work without opening up modules now. Only one tests still fails:
- `SerializationCompatTest` fails because of `AtomicInteger`. 
We need custom serializers for `Atomic*` JDK classes to fix this.

Improve tests for JDK 17

---

src/com/esotericsoftware/kryo/serializers/JavaSerializer.java
test/com/esotericsoftware/kryo/serializers/JavaSerializerTest.java

Fall back to default class resolution if class cannot be loaded with the provided class loader.
Resolves #922

#922 JavaSerializer class resolution fallback

---

src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java

This PR adds some additional safe serializers for common JDK classes. These serializers only rely on the public API of the types and do not require `--add-opens` in JDK17+.
- PatternSerializer
- URISerializer
- UUIDSerializer
- AtomicBooleanSerializer
- AtomicIntegerSerializer
- AtomicLongSerializer
- AtomicReferenceSerializer
Unfortunately, we cannot register these serializers by default in Kryo 5 because it would break backwards compatibility. It makes sense to provide them though and we will register them by default in Kryo 6.
See also #885.

Add additional safe serializers for commonly used JDK classes

---

src/com/esotericsoftware/kryo/unsafe/UnsafeUtil.java

This PR moves initialization for constructor and methods for `DirectBuffer` into a static inner class. This has the effect that users who never use direct buffers, should not see any warnings. 
See #885.

Delay access to DirectBuffers until first use

---

src/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializers.java
test-jdk11/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializersTest.java

This PR adds a helper method to `ImmutableCollectionsSerializers` that registers serializers for all types of `java.util.ImmutableCollections`.
Resolves #923

#923 Add helper to register serializers for `java.util.ImmutableCollections`

---

src/com/esotericsoftware/kryo/serializers/RecordSerializer.java
test-jdk14/com/esotericsoftware/kryo/serializers/RecordSerializerTest.java

This PR adjusts `RecordSerializer` to cache record components, component getters and the canonical constructor. Thew new implementation is about 20x faster than the current one.
The only downside is that I had to remove the existing no-args constructor. This shouldn't be a huge issue, because there was no need for any user to instantiate the `RecordSerializer` themselves.
| Benchmark                        |   Mode |   Cnt    |     Score |   Error  |  Units |
| ------------- | ------------- | ------------- | -------------: | -------------: | ------------- |
| RecordSerializerBenchmark.new   |    thrpt |    4  | 2215445,525 | ± 20885,922 |  ops/s | 
| RecordSerializerBenchmark.old   |    thrpt  |   4  |  105476,509 | ±    1699,820 |   ops/s | 
If we want to stay fully backwards compatible, …

Cache components, getters and constructors in `RecordSerializer`

---

src/com/esotericsoftware/kryo/serializers/ImmutableCollectionsSerializers.java

Declare the built-in serializers for Java's `List.of()`, `Set.of()` and `Map.of()` types to be both `public` and `final`. This makes it easier for Kryo extensions to detect them.
See #943.

Make the ImmutableCollections serializers public and final.

---

src/com/esotericsoftware/kryo/serializers/RecordSerializer.java

I encountered a scenario in production where a record constructor is returned by `recordType.getConstructor()`, but is unusable. Trying to invoke it throws an `IllegalAccessException`. 
Unfortunately, I was unable to reproduce this in a test. It might have something to do with access across module boundaries.

Ensure that record constructors are always accessible

---

src/com/esotericsoftware/kryo/util/DefaultGenerics.java
test-kotlin/com.esotericsoftware.kryo/SerializationTest.kt

Resolves #864.
Thanks a lot @chrisr3 for the suggested fix!

#864 Fix serialization of Kotlin lambdas

---

src/com/esotericsoftware/kryo/serializers/ReflectField.java
src/com/esotericsoftware/kryo/util/Util.java
test/com/esotericsoftware/kryo/serializers/GenericsTest.java
test/com/esotericsoftware/kryo/util/UtilTest.java

This PR fixes type resolution for generic arrays.
Resolves #940 
Resolves #954

#940 Fix type resolution for generic arrays

---

build/assembly-all.xml
main-versioned/pom.xml
main/pom.xml
pom.xml

This allows us to use a more standard Maven project setup and should work with GitHub's Dependency Graph and Dependabot.
See https://github.com/orgs/community/discussions/53539

Move pom-main.xml and pom-versioned.xml to separate folders

---

src/com/esotericsoftware/kryo/serializers/FieldSerializer.java
src/com/esotericsoftware/kryo/util/DefaultGenerics.java
src/com/esotericsoftware/kryo/util/Generics.java
src/com/esotericsoftware/kryo/util/NoGenerics.java

This PR avoids creating `GenericsHierarchy` when `Kryo.setOptimizedGenerics(false)`.

Avoid creating a `GenericsHierarchy` when generics optimization is disabled

---

benchmarks/src/main/java/com/esotericsoftware/kryo/benchmarks/BigDecimalBenchmark.java
src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/serializers/DefaultSerializersTest.java

This is an optimization of the default serializer for `BigDecimal`. Main goal is to avoid constructing `BigDecimal` in the inflated form during deserialization to save on memory and GC pressure of the program that did the deserialization. Avoiding constructing it with a `BigInteger` unscaled value is possible if the unscaled value fits in a `long`. More reasoning behind this can be found in my article: https://medium.com/@gdela/hidden-memory-effects-of-bigdecimal-caa0bfdb1e87
A nice side effect of this is improved throughput of serialization/deserialization for the cases where unscaled value fits in a `long`, i.e. if there are less than ~19 precision digits in the `BigDecimal`:
The changes in the `BigDecimalSerializer` do not change how the serialized form of `BigDecimal` looks like. They …

BigDecimal serializer memory and throughput optimizations

---

src/com/esotericsoftware/kryo/io/ByteBufferInput.java
src/com/esotericsoftware/kryo/io/ByteBufferOutput.java
src/com/esotericsoftware/kryo/io/Input.java
src/com/esotericsoftware/kryo/io/Output.java
src/com/esotericsoftware/kryo/serializers/DefaultSerializers.java
test/com/esotericsoftware/kryo/io/InputOutputTest.java

This is a continuation of #1016 but with the same commits but squashed to one and with fixed the problem with CR/LF (line endings) in `DefaultSerializers`. For reasoning and performance comparison see the #1016.

Avoid allocation in BigDecimal serializer with alternative way to write bytes [crlf corrected].

---

README.md

The link to the blog post about serialising closures that do not implement `Serializable` has an extra comma in the link, leading to a 404 when you click on it. Due to this being a quite trivial no-code PR I have skipped creating an issue, hope that this is okay.

Remove unnecessary comma in the link to the closure blog post

---

test/com/esotericsoftware/kryo/KryoTestCase.java

A failure occurred in ```testPriorityQueueSubclass()``` and ```testPriorityQueue()``` in both the main and main-versioned modules when using NonDex to run these commands:
```
mvn -pl main-versioned edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=com.esotericsoftware.kryo.serializers.DefaultSerializersTest#testPriorityQueueSubclass
```
```
mvn -pl main-versioned edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=com.esotericsoftware.kryo.serializers.DefaultSerializersTest#testPriorityQueue
```
```
mvn -pl main edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=com.esotericsoftware.kryo.serializers.DefaultSerializersTest#testPriorityQueueSubclass
```
```
mvn -pl main edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=com.esotericsoftware.kryo.serializers.DefaultSerializersTest#tes …
```

Fix nondeterministic list comparison in doAssertEquals for PriorityQueue tests
